fix: output image title attribute
adobe/helix-html-pipeline pull request #312
Opened 2023-05-12 14:25 UTC by tmaret

fix #308

2023-05-31 11:26 UTC, tmaret commented
Thanks @tripodsan ! I merged your suggestion commit.

2023-05-31 15:27 UTC, tmaret commented
@tripodsan thanks for point this out, I have pushed commits that include the `data-title` attribute in test fixtures.

2023-05-31 15:28 UTC, tripodsan requested changes
avoid empty string attributes

2023-06-01 07:50 UTC, tmaret commented on test/fixtures/content/image-from-meta.html
> +                <img loading="lazy" alt="Hero image" data-title="" type="image/png" src="./media_a22b1a53edf9b324465d14b2efca169a25d564a0.png?width=750&#x26;format=png&#x26;optimize=medium">
@tripodsan I have pushed the change. It turns out that hastscript outputs empty string properties and skips undefined ones.

2023-06-01 08:29 UTC, tripodsan commented on src/steps/create-pictures.js
> +      'data-title': title === alt ? '' : title,
```suggestion
      'data-title': title === alt ? undefined : title,
```

2023-06-01 16:26 UTC, tripodsan approved these changes

2023-06-01 17:25 UTC, merged