feat: support robots
adobe/helix-html-pipeline pull request #591
Opened 2024-04-18 14:33 UTC by dominique-pfister

2024-04-18 14:54 UTC, tripodsan requested changes
probably also add the config specific surrogate key:
https://github.com/adobe/helix-html-pipeline/blob/ee0e9f7df20609c40792add733b05944ab930dc4/src/json-pipe.js#L94

2024-04-19 06:47 UTC, dominique-pfister commented on src/robots-pipe.js
> +  keys.push(await computeSurrogateKey(`${state.site}--${state.org}_config.json`));
added own method to include that key

2024-04-24 07:50 UTC, tripodsan commented on src/robots-pipe.js
> +  return xfh.split(',').map((v) => v.trim());
filter empty segmetents

2024-04-24 09:06 UTC, dominique-pfister commented on src/robots-pipe.js
> +  )) {
return internal `robots.txt` on preview or when all listed hosts are internal (excluding `www.aem.live`)

2024-04-24 09:06 UTC, dominique-pfister commented on test/robots-pipe.test.js
> +  it('renders robots from live with www.aem.live', async () => {
test to assert `www.aem.live` does not get treated as internal domain

2024-04-24 12:19 UTC, stefan-guggisberg approved these changes

2024-04-24 13:21 UTC, tripodsan approved these changes
I think it would suffice to check if the first xfh segment is not a internal host. but I think this works, too.

2024-04-24 13:43 UTC, merged