add numeric icon feature
adobe/helix-html-pipeline pull request #762
Opened 2024-12-02 16:03 UTC by dkuntze

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

This PR expands the ability to have numbers in icon names while keeping existing functionality. It does fail the regex vulnerability check at https://devina.io/redos-checker (but so does the existing). Will look at seeing if its possible to refactor to make it free of vulnerabilities by making this a tokenizer statemachine.

## Related Issues

Thanks for contributing!

2024-12-02 16:28 UTC, tripodsan requested changes
sorry, but we need to do a full scan of all content of all customers in order to judge the scope of this change. the last time, we created a CSO with exactly this kind of fix.

2024-12-09 13:57 UTC, alexcarol commented
This will also be useful for the ESRI project, thanks @dkuntze!

2025-02-07 20:53 UTC, bstopp commented
Running into an issue w/ Jet2.

This successfully gets converted into an icon:
`:Jet2Holidays:`

This does not:

`:Jet2holidays-no-strapline:`

both should work.

2025-02-11 08:35 UTC, tripodsan commented
here some false positives that were found scanning the content:

* `g) and 1:00-3:00 PM. H`
* `6:00AM-6:00 PM MT`
* ` 11:30am-12:30pm CT`
* `c HEVC 4:2:2 10 bit`
* `色情報が半分の4:2:2素材では、エッ`
* `月1日木曜日14:00-19:00`

2025-02-11 18:56 UTC, dkuntze commented
I'm starting to think this is an impossible task. I may just document what works and what doesn't and call it a day.

2025-02-11 19:50 UTC, dkuntze commented
@tripodsan I gave it another go and added your false positives to the tests

2025-02-11 21:05 UTC, tripodsan commented on src/steps/rewrite-icons.js
> +      if (/[\d:T]/.test(beforeChar) || /[\d:]/.test(afterChar)) {
this is a very expensive test to check for 1 character :-)

2025-02-11 21:06 UTC, tripodsan commented on src/steps/rewrite-icons.js
> +        return idx + 1;
what about the rest of the text? eg `00:00:00 and :icon:` ?

2025-02-11 21:06 UTC, tripodsan requested changes
not quite, I think.

2025-02-11 21:26 UTC, dkuntze commented on src/steps/rewrite-icons.js
> +        return idx + 1;
I added tests for `:icon:` to work (literal) and `00:00:00` to fail.

Both are working.

2025-02-11 21:26 UTC, dkuntze commented on src/steps/rewrite-icons.js
> +      if (/[\d:T]/.test(beforeChar) || /[\d:]/.test(afterChar)) {
I removed the test.

2025-02-12 10:15 UTC, tripodsan commented on test/fixtures/content/icons.html
> -        <p>Hello <span class="icon icon-red"></span> banner.</p>
the whitespace should not be removed

2025-02-12 21:37 UTC, tripodsan requested changes
I appreciate the effort, but this is getting too complicated and potentially a performance drain. I think the previous iteration was ok, besides the `return` at the wrong place.

2026-07-31 15:23 UTC, closed without merging